defrault_index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

pruebas:
    path:     /pruebas
    defaults: { _controller: AppBundle:Default:pruebas }
    
homeback:
    path:     /home
    defaults: { _controller: AppBundle:Default:home }

regisClient:
    path:     /cliente/new
    defaults: { _controller: AppBundle:Cliente:new }

listarClient:
    path:     /cliente/listar
    defaults: { _controller: AppBundle:Cliente:listCliente }
    
searchClient:
    path:     /cliente/search/{search}
    defaults: { _controller: AppBundle:Cliente:searchCliente , search:null }
    
editarClient:
    path:     /cliente/editar/{id}
    defaults: { _controller: AppBundle:Cliente:editarCliente }

idClient:
    path:     /cliente/{id}
    defaults: { _controller: AppBundle:Cliente:cliente, id:null }
    
regisPedido:
    path:     /pedido/new
    defaults: { _controller: AppBundle:Pedido:new }

listarPedido:
    path:     /pedido/listar
    defaults: { _controller: AppBundle:Pedido:listar }

clientePedido:
    path:     /pedido/clientes
    defaults: { _controller: AppBundle:Cliente:clientePedido }

idPedido:
    path:     /pedido/{id}
    defaults: { _controller: AppBundle:Pedido:pedido, id:null }
    

pagadoPedido:
    path:     /pedido/update/pagar/{id}
    defaults: { _controller: AppBundle:Pedido:pagar, id:null }

entregadoPedido:
    path:     /pedido/update/entregar/{id}
    defaults: { _controller: AppBundle:Pedido:entregar, id:null }
    
searchPedido:
    path:     /pedido/search/{search}
    defaults: { _controller: AppBundle:Pedido:searchPedido , search:null }
    
clientePedidos:
    path:     /cliente/pedidos/{id}
    defaults: { _controller: AppBundle:Pedido:clientePedidos , id:null }

porPagarPedidos:
    path:     /pedido/por/pagar
    defaults: { _controller: AppBundle:Pedido:porpagar }

porEntregarPedidos:
    path:     /pedido/por/entregar
    defaults: { _controller: AppBundle:Pedido:porEntregar }

newMotivo:
    path:     /motivo/new
    defaults: { _controller: AppBundle:Motivo:new }
    
listarMotivo:
    path: /motivo/listar
    defaults: { _controller: AppBundle:Motivo:listar }
    
editarMotivo:
    path:     /motivo/editar/{id}
    defaults: { _controller: AppBundle:Motivo:editar , id:null }
    
idMotivo:
    path:     /motivo/{id}
    defaults: { _controller: AppBundle:Motivo:motivo, id:null }
    
removeMotivo:
    path:     /motivo/remove/{id}
    defaults: { _controller: AppBundle:Motivo:remove, id:null }
    
newDedicatoria:
    path:     /dedicatoria/new
    defaults: { _controller: AppBundle:Dedicatoria:new }
    
listarDedicatoria:
    path: /dedicatoria/listar
    defaults: { _controller: AppBundle:Dedicatoria:listar }

listarPorMotivoDedicatoria:
    path: /dedicatoria/por-motivo/{id}
    defaults: { _controller: AppBundle:Dedicatoria:listarPorMotivo, id:null }
    
idDedicatoria:
    path:     /dedicatoria/{id}
    defaults: { _controller: AppBundle:Dedicatoria:dedicatoria, id:null }
    
editarDedicatoria:
    path:     /dedicatoria/editar/{id}
    defaults: { _controller: AppBundle:Dedicatoria:editar , id:null }
    
removeDedicatoria:
    path:     /dedicatoria/remove/{id}
    defaults: { _controller: AppBundle:Dedicatoria:remove, id:null }
    
removeDedicatoria:
    path:     /dedicatoria/remove/{id}
    defaults: { _controller: AppBundle:Dedicatoria:remove, id:null }
    
newImagenTarjeta:
    path:     /imagen-tarjeta/new
    defaults: { _controller: AppBundle:ImagenTarjeta:new }
    
listarImagenes:
    path: /imagen-tarjeta/listar
    defaults: { _controller: AppBundle:ImagenTarjeta:listar }

idImagenTarjeta:
    path:     /imagen-tarjeta/{id}
    defaults: { _controller: AppBundle:ImagenTarjeta:imagenTarjeta, id:null }

editarImagenTarjeta:
    path:     /imagen-tarjeta/editar/{id}
    defaults: { _controller: AppBundle:ImagenTarjeta:editar , id:null }
    
removeImagenTarjeta:
    path:     /imagen-tarjeta/remove/{id}
    defaults: { _controller: AppBundle:ImagenTarjeta:remove, id:null }

listarPorMotivoImagenes:
    path: /imagen-tarjeta/por-motivo/{id}
    defaults: { _controller: AppBundle:ImagenTarjeta:listarPorMotivo , id:null }